"""Initialize a fresh Azure SQL database using deployment credentials; no secrets printed."""
import argparse
import json
import os
from pathlib import Path
import sys
from urllib.parse import urlparse,unquote,quote
root=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(root))
p=argparse.ArgumentParser();p.add_argument('--parameters',required=True,type=Path);args=p.parse_args()
values={k:v['value'] for k,v in json.loads(args.parameters.read_text())['parameters'].items()}
runtime=urlparse(values['databaseUrl']);password=unquote(runtime.password)
os.environ['DATABASE_URL']=f"mssql+pytds://systracker_bootstrap:{quote(values['sqlAdminPassword'],safe='')}@{runtime.hostname}:1433/systracker"
os.environ['SECRET_KEY']=values['sessionSecret']
# This tool only initializes schema and database authorization. Account email bootstrap runs in Azure.
os.environ['APP_ENV']='development'
from web import create_app
from web.models import db
from sqlalchemy import text
app=create_app()
with app.app_context():
    db.create_all()
    # Password is generated by deploy-azure.py; never interpolate arbitrary identifiers.
    if not all(c.isalnum() or c in '_-' for c in password):raise SystemExit('Unexpected generated password format.')
    existing=db.session.execute(text("SELECT name FROM sys.database_principals WHERE name = 'systracker_app'" )).first()
    if not existing:db.session.execute(text("CREATE USER [systracker_app] WITH PASSWORD = '"+password+"'"))
    for permission in ('SELECT','INSERT','UPDATE','DELETE'):
        db.session.execute(text(f'GRANT {permission} ON SCHEMA::dbo TO [systracker_app]'))
    db.session.commit()
print('Schema initialized. Runtime user has data permissions and no schema-management role.')
